<?php

namespace ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * items_orderedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class items_orderedRepository extends EntityRepository
{
}
