<?php

namespace ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PizzaOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizzaOrderRepository extends EntityRepository
{
}
