shop_homepage:
    path:     /hello/{name}
    defaults: { _controller: ShopBundle:Default:index }


product:
    resource: "@ShopBundle/Controller/"
    type: annotation


login:
    path: /login
    defaults: { _controller: ShopBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout